# Generated by Django 4.2.27 on 2025-12-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Em espera'), ('PREPARING', 'Em preparação'), ('OUT_FOR_DELIVERY', 'Saiu para entrega'), ('DELIVERED', 'Entregue'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20),
        ),
    ]
