# Generated by Django 4.2.27 on 2025-12-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_food_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image_url',
            field=models.URLField(blank=True, max_length=15000),
        ),
    ]
