# Generated by Django 4.2.27 on 2025-12-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_food_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
